export const menuItems = [{
        id: 1,
        label: "Menu",
        isTitle: true,
        user: [],
    },
    {
        id: 2,
        label: "Home",
        icon: "bx-home-circle",
        link: "/home",
        component: "Home/Index",
        name: "Home",
        user: [],
    },
    {
        id: 5,
        label: "Theses",
        icon: "bxs-book-bookmark",
        link: "/theses",
        component: "Modules/Theses/Index",
        name: "Modules/Theses",
        user: ['Super Administrator'],
    },
    {
        id: 7,
        label: "Requests",
        icon: "bx-git-pull-request",
        link: "/requests",
        component: "Modules/Requests/Index",
        name: "Modules/Requests",
        user: ['Super Administrator'],
    },
    {
        id: 6,
        label: "Registrants",
        icon: "bxs-user-plus",
        link: "/registrants",
        component: "Modules/Registrants/Index",
        name: "Modules/Registrants",
        user: ['Super Administrator'],
    },
    {
        id: 3,
        label: "Users",
        icon: "bxs-face",
        link: "/users",
        component: "Modules/Users/Index",
        name: "Modules/Users",
        user: ['Super Administrator'],
    },
    {
        id: 4,
        label: "Policies",
        icon: "bxs-notepad",
        link: "/policies",
        component: "Modules/Policies/Index",
        name: "Modules/Policies",
        user: ['Super Administrator'],
    },

];