export const menuItems = [{
        id: 1,
        label: "Menu",
        isTitle: true,
        user: [],
    },
    {
        id: 2,
        label: "Home",
        icon: "bx-home-circle",
        link: "/home",
        component: "Home/Index",
        name: "Home",
        user: [],
    },
    {
        id: 5,
        label: "Theses",
        icon: "bxs-book-bookmark",
        link: "/theses",
        component: "Modules/Theses/Index",
        name: "Modules/Theses",
        user: ['Super Administrator'],
    },
    {
        id: 3,
        label: "Users",
        icon: "bxs-face",
        link: "/users",
        component: "Modules/Users/Index",
        name: "Modules/Users",
        user: ['Super Administrator'],
    },
    {
        id: 4,
        label: "Policies",
        icon: "bxs-notepad",
        link: "/policies",
        component: "Modules/Policies/Index",
        name: "Modules/Policies",
        user: ['Super Administrator'],
    },

];